//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;

namespace SourceFEWSAdapter.FEWSPI {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    [System.Xml.Serialization.XmlRootAttribute("Diag", Namespace="http://www.wldelft.nl/fews/PI", IsNullable=false)]
    public partial class DiagComplexType {
        
        private LineComplexType[] lineField;
        
        private string commentField;
        
        private double versionField;
        
        public DiagComplexType() {
            this.versionField = 1.2D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("line")]
        public LineComplexType[] line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class LineComplexType {
        
        private sbyte levelField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    [System.Xml.Serialization.XmlRootAttribute("parameters", Namespace="http://www.wldelft.nl/fews/PI", IsNullable=false)]
    public partial class ModelParametersComplexType {
        
        private string[] modifierTypeField;
        
        private ModelParameterGroupComplexType[] groupField;
        
        private versionString versionField;
        
        public ModelParametersComplexType() {
            this.versionField = versionString.Item15;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("modifierType")]
        public string[] modifierType {
            get {
                return this.modifierTypeField;
            }
            set {
                this.modifierTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group")]
        public ModelParameterGroupComplexType[] group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public versionString version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class ModelParameterGroupComplexType {
        
        private string descriptionField;
        
        private string locationIdField;
        
        private string modelField;
        
        private PeriodConditionComplexType validPeriodField;
        
        private object[] itemsField;
        
        private string idField;
        
        private string nameField;
        
        private bool readonlyField;
        
        private bool modifiedField;
        
        public ModelParameterGroupComplexType() {
            this.readonlyField = false;
            this.modifiedField = false;
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string locationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public PeriodConditionComplexType validPeriod {
            get {
                return this.validPeriodField;
            }
            set {
                this.validPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ensemble", typeof(EnsembleComplexType))]
        [System.Xml.Serialization.XmlElementAttribute("parameter", typeof(ModelParameterComplexType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool @readonly {
            get {
                return this.readonlyField;
            }
            set {
                this.readonlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class PeriodConditionComplexType {
        
        private double timeZoneField;
        
        private bool timeZoneFieldSpecified;
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        public double timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeZoneSpecified {
            get {
                return this.timeZoneFieldSpecified;
            }
            set {
                this.timeZoneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("day", typeof(string), DataType="gDay")]
        [System.Xml.Serialization.XmlElementAttribute("endDate", typeof(DateTimeComplexType))]
        [System.Xml.Serialization.XmlElementAttribute("endMonthDay", typeof(string), DataType="gMonthDay")]
        [System.Xml.Serialization.XmlElementAttribute("month", typeof(string), DataType="gMonth")]
        [System.Xml.Serialization.XmlElementAttribute("monthDay", typeof(string), DataType="gMonthDay")]
        [System.Xml.Serialization.XmlElementAttribute("startDate", typeof(DateTimeComplexType))]
        [System.Xml.Serialization.XmlElementAttribute("startMonthDay", typeof(string), DataType="gMonthDay")]
        [System.Xml.Serialization.XmlElementAttribute("validAfterDate", typeof(DateTimeComplexType))]
        [System.Xml.Serialization.XmlElementAttribute("validBeforeDate", typeof(DateTimeComplexType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class DateTimeComplexType {
        
        private DateTime dateField;
        
        private string timeField;
        
        /// <remarks/>
        [XmlAttribute(DataType="date")]
        public DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        day,
        
        /// <remarks/>
        endDate,
        
        /// <remarks/>
        endMonthDay,
        
        /// <remarks/>
        month,
        
        /// <remarks/>
        monthDay,
        
        /// <remarks/>
        startDate,
        
        /// <remarks/>
        startMonthDay,
        
        /// <remarks/>
        validAfterDate,
        
        /// <remarks/>
        validBeforeDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class EnsembleComplexType {
        
        private object itemField;
        
        private ModelParameterComplexType[] parameterField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ensembleMember", typeof(EnsembleMemberComplexType))]
        [System.Xml.Serialization.XmlElementAttribute("ensembleMemberRange", typeof(EnsembleMemberRangeComplexType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public ModelParameterComplexType[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class EnsembleMemberComplexType {
        
        private string indexField;
        
        private double weightField;
        
        private bool weightFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class EnsembleMemberRangeComplexType {
        
        private string startField;
        
        private string endField;
        
        private double weightField;
        
        private bool weightFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class ModelParameterComplexType {
        
        private string descriptionField;
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("boolValue", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("dateTimeValue", typeof(DateTimeComplexType))]
        [System.Xml.Serialization.XmlElementAttribute("dblValue", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("intValue", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("stringValue", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("table", typeof(GlobalTableComplexType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class GlobalTableComplexType {
        
        private ColumnIdsComplexType columnIdsField;
        
        private ColumnTypesComplexType columnTypesField;
        
        private RowComplexType[] rowField;
        
        /// <remarks/>
        public ColumnIdsComplexType columnIds {
            get {
                return this.columnIdsField;
            }
            set {
                this.columnIdsField = value;
            }
        }
        
        /// <remarks/>
        public ColumnTypesComplexType columnTypes {
            get {
                return this.columnTypesField;
            }
            set {
                this.columnTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("row")]
        public RowComplexType[] row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class ColumnIdsComplexType {
        
        private string aField;
        
        private string bField;
        
        private string cField;
        
        private string dField;
        
        private string eField;
        
        private string fField;
        
        private string gField;
        
        private string hField;
        
        private string iField;
        
        private string jField;
        
        private string kField;
        
        private string lField;
        
        private string mField;
        
        private string nField;
        
        private string oField;
        
        private string pField;
        
        private string qField;
        
        private string rField;
        
        private string sField;
        
        private string tField;
        
        private string uField;
        
        private string vField;
        
        private string wField;
        
        private string xField;
        
        private string yField;
        
        private string zField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string D {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E {
            get {
                return this.eField;
            }
            set {
                this.eField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F {
            get {
                return this.fField;
            }
            set {
                this.fField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string G {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string H {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string I {
            get {
                return this.iField;
            }
            set {
                this.iField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string J {
            get {
                return this.jField;
            }
            set {
                this.jField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string L {
            get {
                return this.lField;
            }
            set {
                this.lField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string M {
            get {
                return this.mField;
            }
            set {
                this.mField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string O {
            get {
                return this.oField;
            }
            set {
                this.oField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string S {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string U {
            get {
                return this.uField;
            }
            set {
                this.uField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string W {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class ColumnTypesComplexType {
        
        private ValueTypeEnumStringType aField;
        
        private ValueTypeEnumStringType bField;
        
        private bool bFieldSpecified;
        
        private ValueTypeEnumStringType cField;
        
        private bool cFieldSpecified;
        
        private ValueTypeEnumStringType dField;
        
        private bool dFieldSpecified;
        
        private ValueTypeEnumStringType eField;
        
        private bool eFieldSpecified;
        
        private ValueTypeEnumStringType fField;
        
        private bool fFieldSpecified;
        
        private ValueTypeEnumStringType gField;
        
        private bool gFieldSpecified;
        
        private ValueTypeEnumStringType hField;
        
        private bool hFieldSpecified;
        
        private ValueTypeEnumStringType iField;
        
        private bool iFieldSpecified;
        
        private ValueTypeEnumStringType jField;
        
        private bool jFieldSpecified;
        
        private ValueTypeEnumStringType kField;
        
        private bool kFieldSpecified;
        
        private ValueTypeEnumStringType lField;
        
        private bool lFieldSpecified;
        
        private ValueTypeEnumStringType mField;
        
        private bool mFieldSpecified;
        
        private ValueTypeEnumStringType nField;
        
        private bool nFieldSpecified;
        
        private ValueTypeEnumStringType oField;
        
        private bool oFieldSpecified;
        
        private ValueTypeEnumStringType pField;
        
        private bool pFieldSpecified;
        
        private ValueTypeEnumStringType qField;
        
        private bool qFieldSpecified;
        
        private ValueTypeEnumStringType rField;
        
        private bool rFieldSpecified;
        
        private ValueTypeEnumStringType sField;
        
        private bool sFieldSpecified;
        
        private ValueTypeEnumStringType tField;
        
        private bool tFieldSpecified;
        
        private ValueTypeEnumStringType uField;
        
        private bool uFieldSpecified;
        
        private ValueTypeEnumStringType vField;
        
        private bool vFieldSpecified;
        
        private ValueTypeEnumStringType wField;
        
        private bool wFieldSpecified;
        
        private ValueTypeEnumStringType xField;
        
        private bool xFieldSpecified;
        
        private ValueTypeEnumStringType yField;
        
        private bool yFieldSpecified;
        
        private ValueTypeEnumStringType zField;
        
        private bool zFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType A {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType B {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BSpecified {
            get {
                return this.bFieldSpecified;
            }
            set {
                this.bFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CSpecified {
            get {
                return this.cFieldSpecified;
            }
            set {
                this.cFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType D {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DSpecified {
            get {
                return this.dFieldSpecified;
            }
            set {
                this.dFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType E {
            get {
                return this.eField;
            }
            set {
                this.eField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESpecified {
            get {
                return this.eFieldSpecified;
            }
            set {
                this.eFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType F {
            get {
                return this.fField;
            }
            set {
                this.fField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FSpecified {
            get {
                return this.fFieldSpecified;
            }
            set {
                this.fFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType G {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GSpecified {
            get {
                return this.gFieldSpecified;
            }
            set {
                this.gFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType H {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HSpecified {
            get {
                return this.hFieldSpecified;
            }
            set {
                this.hFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType I {
            get {
                return this.iField;
            }
            set {
                this.iField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ISpecified {
            get {
                return this.iFieldSpecified;
            }
            set {
                this.iFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType J {
            get {
                return this.jField;
            }
            set {
                this.jField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JSpecified {
            get {
                return this.jFieldSpecified;
            }
            set {
                this.jFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType K {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KSpecified {
            get {
                return this.kFieldSpecified;
            }
            set {
                this.kFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType L {
            get {
                return this.lField;
            }
            set {
                this.lField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LSpecified {
            get {
                return this.lFieldSpecified;
            }
            set {
                this.lFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType M {
            get {
                return this.mField;
            }
            set {
                this.mField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MSpecified {
            get {
                return this.mFieldSpecified;
            }
            set {
                this.mFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NSpecified {
            get {
                return this.nFieldSpecified;
            }
            set {
                this.nFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType O {
            get {
                return this.oField;
            }
            set {
                this.oField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OSpecified {
            get {
                return this.oFieldSpecified;
            }
            set {
                this.oFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PSpecified {
            get {
                return this.pFieldSpecified;
            }
            set {
                this.pFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QSpecified {
            get {
                return this.qFieldSpecified;
            }
            set {
                this.qFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RSpecified {
            get {
                return this.rFieldSpecified;
            }
            set {
                this.rFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType S {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SSpecified {
            get {
                return this.sFieldSpecified;
            }
            set {
                this.sFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TSpecified {
            get {
                return this.tFieldSpecified;
            }
            set {
                this.tFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType U {
            get {
                return this.uField;
            }
            set {
                this.uField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USpecified {
            get {
                return this.uFieldSpecified;
            }
            set {
                this.uFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType V {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VSpecified {
            get {
                return this.vFieldSpecified;
            }
            set {
                this.vFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType W {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WSpecified {
            get {
                return this.wFieldSpecified;
            }
            set {
                this.wFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YSpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueTypeEnumStringType Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public enum ValueTypeEnumStringType {
        
        /// <remarks/>
        boolean,
        
        /// <remarks/>
        @int,
        
        /// <remarks/>
        @float,
        
        /// <remarks/>
        @double,
        
        /// <remarks/>
        @string,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class RowComplexType {
        
        private string aField;
        
        private string bField;
        
        private string cField;
        
        private string dField;
        
        private string eField;
        
        private string fField;
        
        private string gField;
        
        private string hField;
        
        private string iField;
        
        private string jField;
        
        private string kField;
        
        private string lField;
        
        private string mField;
        
        private string nField;
        
        private string oField;
        
        private string pField;
        
        private string qField;
        
        private string rField;
        
        private string sField;
        
        private string tField;
        
        private string uField;
        
        private string vField;
        
        private string wField;
        
        private string xField;
        
        private string yField;
        
        private string zField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string D {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E {
            get {
                return this.eField;
            }
            set {
                this.eField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F {
            get {
                return this.fField;
            }
            set {
                this.fField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string G {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string H {
            get {
                return this.hField;
            }
            set {
                this.hField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string I {
            get {
                return this.iField;
            }
            set {
                this.iField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string J {
            get {
                return this.jField;
            }
            set {
                this.jField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string K {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string L {
            get {
                return this.lField;
            }
            set {
                this.lField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string M {
            get {
                return this.mField;
            }
            set {
                this.mField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string N {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string O {
            get {
                return this.oField;
            }
            set {
                this.oField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Q {
            get {
                return this.qField;
            }
            set {
                this.qField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string R {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string S {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string T {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string U {
            get {
                return this.uField;
            }
            set {
                this.uField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string V {
            get {
                return this.vField;
            }
            set {
                this.vField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string W {
            get {
                return this.wField;
            }
            set {
                this.wField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        boolValue,
        
        /// <remarks/>
        dateTimeValue,
        
        /// <remarks/>
        dblValue,
        
        /// <remarks/>
        intValue,
        
        /// <remarks/>
        stringValue,
        
        /// <remarks/>
        table,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public enum versionString {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.2")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.3")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.4")]
        Item14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.5")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.6")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.7")]
        Item17,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.8")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.9")]
        Item19,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.10")]
        Item110,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    [System.Xml.Serialization.XmlRootAttribute("Run", Namespace="http://www.wldelft.nl/fews/PI", IsNullable=false)]
    public partial class RunComplexType {
        
        private logLevelString logLevelField;
        
        private bool logLevelFieldSpecified;
        
        private double timeZoneField;
        
        private DateTimeComplexType startDateTimeField;
        
        private DateTimeComplexType endDateTimeField;
        
        private DateTimeComplexType time0Field;
        
        private DateTimeComplexType lastObservationDateTimeField;
        
        private string workDirField;
        
        private string[] inputParameterFileField;
        
        private string[] inputStateDescriptionFileField;
        
        private string[] inputTimeSeriesFileField;
        
        private string[] inputMapStackFileField;
        
        private string[] inputNetcdfFileField;
        
        private string[] inputLongitudinalProfilesFileField;
        
        private string[] inputRatingCurveFileField;
        
        private string outputDiagnosticFileField;
        
        private string outputStateDescriptionFileField;
        
        private string[] outputTimeSeriesFileField;
        
        private string[] outputMapStackFileField;
        
        private string[] outputNetcdfFileField;
        
        private string[] outputLongitudinalProfilesFileField;
        
        private PropertiesComplexType propertiesField;
        
        private versionString versionField;
        
        /// <remarks/>
        public logLevelString logLevel {
            get {
                return this.logLevelField;
            }
            set {
                this.logLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool logLevelSpecified {
            get {
                return this.logLevelFieldSpecified;
            }
            set {
                this.logLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeComplexType startDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeComplexType endDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeComplexType time0 {
            get {
                return this.time0Field;
            }
            set {
                this.time0Field = value;
            }
        }
        
        /// <remarks/>
        public DateTimeComplexType lastObservationDateTime {
            get {
                return this.lastObservationDateTimeField;
            }
            set {
                this.lastObservationDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string workDir {
            get {
                return this.workDirField;
            }
            set {
                this.workDirField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputParameterFile")]
        public string[] inputParameterFile {
            get {
                return this.inputParameterFileField;
            }
            set {
                this.inputParameterFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputStateDescriptionFile")]
        public string[] inputStateDescriptionFile {
            get {
                return this.inputStateDescriptionFileField;
            }
            set {
                this.inputStateDescriptionFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputTimeSeriesFile")]
        public string[] inputTimeSeriesFile {
            get {
                return this.inputTimeSeriesFileField;
            }
            set {
                this.inputTimeSeriesFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputMapStackFile")]
        public string[] inputMapStackFile {
            get {
                return this.inputMapStackFileField;
            }
            set {
                this.inputMapStackFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputNetcdfFile")]
        public string[] inputNetcdfFile {
            get {
                return this.inputNetcdfFileField;
            }
            set {
                this.inputNetcdfFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputLongitudinalProfilesFile")]
        public string[] inputLongitudinalProfilesFile {
            get {
                return this.inputLongitudinalProfilesFileField;
            }
            set {
                this.inputLongitudinalProfilesFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inputRatingCurveFile")]
        public string[] inputRatingCurveFile {
            get {
                return this.inputRatingCurveFileField;
            }
            set {
                this.inputRatingCurveFileField = value;
            }
        }
        
        /// <remarks/>
        public string outputDiagnosticFile {
            get {
                return this.outputDiagnosticFileField;
            }
            set {
                this.outputDiagnosticFileField = value;
            }
        }
        
        /// <remarks/>
        public string outputStateDescriptionFile {
            get {
                return this.outputStateDescriptionFileField;
            }
            set {
                this.outputStateDescriptionFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outputTimeSeriesFile")]
        public string[] outputTimeSeriesFile {
            get {
                return this.outputTimeSeriesFileField;
            }
            set {
                this.outputTimeSeriesFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outputMapStackFile")]
        public string[] outputMapStackFile {
            get {
                return this.outputMapStackFileField;
            }
            set {
                this.outputMapStackFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outputNetcdfFile")]
        public string[] outputNetcdfFile {
            get {
                return this.outputNetcdfFileField;
            }
            set {
                this.outputNetcdfFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outputLongitudinalProfilesFile")]
        public string[] outputLongitudinalProfilesFile {
            get {
                return this.outputLongitudinalProfilesFileField;
            }
            set {
                this.outputLongitudinalProfilesFileField = value;
            }
        }
        
        /// <remarks/>
        public PropertiesComplexType properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public versionString version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public enum logLevelString {
        
        /// <remarks/>
        fatal,
        
        /// <remarks/>
        error,
        
        /// <remarks/>
        warn,
        
        /// <remarks/>
        info,
        
        /// <remarks/>
        debug,
        
        /// <remarks/>
        trace,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class PropertiesComplexType {
        
        private string descriptionField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bool", typeof(BoolPropertyComplexType))]
        [System.Xml.Serialization.XmlElementAttribute("float", typeof(FloatPropertyComplexType))]
        [System.Xml.Serialization.XmlElementAttribute("int", typeof(IntPropertyComplexType))]
        [System.Xml.Serialization.XmlElementAttribute("string", typeof(StringPropertyComplexType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class BoolPropertyComplexType {
        
        private string descriptionField;
        
        private string keyField;
        
        private bool valueField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class FloatPropertyComplexType {
        
        private string descriptionField;
        
        private string keyField;
        
        private float valueField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class IntPropertyComplexType {
        
        private string descriptionField;
        
        private string keyField;
        
        private int valueField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class StringPropertyComplexType {
        
        private string descriptionField;
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    [System.Xml.Serialization.XmlRootAttribute("TimeSeries", Namespace="http://www.wldelft.nl/fews/PI", IsNullable=false)]
    public partial class TimeSeriesCollectionComplexType {
        
        private double timeZoneField;
        
        private TimeSeriesComplexType[] seriesField;
        
        private versionString versionField;
        
        public TimeSeriesCollectionComplexType() {
            this.timeZoneField = 0D;
            this.versionField = versionString.Item12;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("series")]
        public TimeSeriesComplexType[] series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(versionString.Item12)]
        public versionString version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class TimeSeriesComplexType {
        
        private HeaderComplexType headerField;
        
        private EventComplexType[] eventField;
        
        private string commentField;
        
        /// <remarks/>
        public HeaderComplexType header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("event")]
        public EventComplexType[] @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class HeaderComplexType {
        
        private timeSeriesType typeField;
        
        private string locationIdField;
        
        private string parameterIdField;
        
        private string[] qualifierIdField;
        
        private string ensembleIdField;
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private TimeStepComplexType timeStepField;
        
        private DateTimeComplexType startDateField;
        
        private DateTimeComplexType endDateField;
        
        private DateTimeComplexType forecastDateField;
        
        private double missValField;
        
        private string longNameField;
        
        private string stationNameField;
        
        private double latField;
        
        private bool latFieldSpecified;
        
        private double lonField;
        
        private bool lonFieldSpecified;
        
        private double xField;
        
        private bool xFieldSpecified;
        
        private double yField;
        
        private bool yFieldSpecified;
        
        private double zField;
        
        private bool zFieldSpecified;
        
        private string unitsField;
        
        private string sourceOrganisationField;
        
        private string sourceSystemField;
        
        private string fileDescriptionField;
        
        private System.DateTime creationDateField;
        
        private bool creationDateFieldSpecified;
        
        private System.DateTime creationTimeField;
        
        private bool creationTimeFieldSpecified;
        
        private string regionField;
        
        private HighLevelThresholdsComplexType[] thresholdsField;
        
        public HeaderComplexType() {
            this.missValField = double.NaN;
        }
        
        /// <remarks/>
        public timeSeriesType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string locationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public string parameterId {
            get {
                return this.parameterIdField;
            }
            set {
                this.parameterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("qualifierId")]
        public string[] qualifierId {
            get {
                return this.qualifierIdField;
            }
            set {
                this.qualifierIdField = value;
            }
        }
        
        /// <remarks/>
        public string ensembleId {
            get {
                return this.ensembleIdField;
            }
            set {
                this.ensembleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ensembleMemberId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ensembleMemberIndex", typeof(string), DataType="nonNegativeInteger")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public TimeStepComplexType timeStep {
            get {
                return this.timeStepField;
            }
            set {
                this.timeStepField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeComplexType startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeComplexType endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public DateTimeComplexType forecastDate {
            get {
                return this.forecastDateField;
            }
            set {
                this.forecastDateField = value;
            }
        }
        
        /// <remarks/>
        public double missVal {
            get {
                return this.missValField;
            }
            set {
                this.missValField = value;
            }
        }
        
        /// <remarks/>
        public string longName {
            get {
                return this.longNameField;
            }
            set {
                this.longNameField = value;
            }
        }
        
        /// <remarks/>
        public string stationName {
            get {
                return this.stationNameField;
            }
            set {
                this.stationNameField = value;
            }
        }
        
        /// <remarks/>
        public double lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latSpecified {
            get {
                return this.latFieldSpecified;
            }
            set {
                this.latFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lonSpecified {
            get {
                return this.lonFieldSpecified;
            }
            set {
                this.lonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zSpecified {
            get {
                return this.zFieldSpecified;
            }
            set {
                this.zFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        public string sourceOrganisation {
            get {
                return this.sourceOrganisationField;
            }
            set {
                this.sourceOrganisationField = value;
            }
        }
        
        /// <remarks/>
        public string sourceSystem {
            get {
                return this.sourceSystemField;
            }
            set {
                this.sourceSystemField = value;
            }
        }
        
        /// <remarks/>
        public string fileDescription {
            get {
                return this.fileDescriptionField;
            }
            set {
                this.fileDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationDateSpecified {
            get {
                return this.creationDateFieldSpecified;
            }
            set {
                this.creationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime creationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationTimeSpecified {
            get {
                return this.creationTimeFieldSpecified;
            }
            set {
                this.creationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("highLevelThreshold", IsNullable=false)]
        public HighLevelThresholdsComplexType[] thresholds {
            get {
                return this.thresholdsField;
            }
            set {
                this.thresholdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public enum timeSeriesType {
        
        /// <remarks/>
        accumulative,
        
        /// <remarks/>
        instantaneous,
        
        /// <remarks/>
        mean,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        ensembleMemberId,
        
        /// <remarks/>
        ensembleMemberIndex,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class TimeStepComplexType {
        
        private timeStepUnitEnumStringType unitField;
        
        private string dividerField;
        
        private string multiplierField;
        
        public TimeStepComplexType() {
            this.dividerField = "1";
            this.multiplierField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public timeStepUnitEnumStringType unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string divider {
            get {
                return this.dividerField;
            }
            set {
                this.dividerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public enum timeStepUnitEnumStringType {
        
        /// <remarks/>
        second,
        
        /// <remarks/>
        minute,
        
        /// <remarks/>
        hour,
        
        /// <remarks/>
        day,
        
        /// <remarks/>
        week,
        
        /// <remarks/>
        month,
        
        /// <remarks/>
        year,
        
        /// <remarks/>
        nonequidistant,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class HighLevelThresholdsComplexType {
        
        private string idField;
        
        private string nameField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.wldelft.nl/fews/PI")]
    public partial class EventComplexType {
        
        private System.DateTime dateField;
        
        private string timeField;
        
        private double valueField;
        
        private int flagField;
        
        private bool flagFieldSpecified;
        
        private string commentField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flagSpecified {
            get {
                return this.flagFieldSpecified;
            }
            set {
                this.flagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
    }
}
